# Generated by Django 5.0.3 on 2024-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csepresident',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/csepresident'),
        ),
        migrations.AddField(
            model_name='csesecretorypresident',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/csesecretory'),
        ),
        migrations.AddField(
            model_name='csevicepresident',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/csevicepresident'),
        ),
    ]
