# Generated by Django 5.0.3 on 2024-03-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_csepresident_image_csesecretorypresident_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Csesecretorypresident',
            new_name='Csesecretory',
        ),
    ]
